version: '2'
services:
  clusterf-proxy:
    image: andymacdonald/clusterf-chaos-proxy
    environment:
      JAVA_OPTS: "-Dchaos.strategy=RANDOM_HAVOC -Ddestination.hostProtocolAndPort=http://database:3100 -Dchaos.strategy.delayResponse.random.maxSeconds=10"
    ports:
      - "8088:8080"
  database:
    image: mitchallen/random-server
    expose:
    - 3100
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./queries/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: [ "postgres", "-c", "log_statement=all" ]
  fastapi-app:
    build:
      context: .
      dockerfile: app/Dockerfile-fastapi
    ports:
      - "8083:80"
    depends_on:
      - postgres-db


